In [2]:
import sys
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [12]:
a

array([1, 2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b.dtype

dtype('float64')

In [16]:
d = np.array([{'a': 1}, sys])

In [17]:
d.dtype

dtype('O')

In [18]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [19]:
A.shape

(2, 3)

In [20]:
A.ndim

2

In [21]:
A.size

6

In [22]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [23]:
B.shape

(2, 2, 3)

In [24]:
B.ndim

3

In [25]:
B.size

12

In [26]:
type(B[0])

numpy.ndarray

In [27]:
# Square matrix
A = np.array([
#.  1. 2. 3.
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9], #2
])

In [28]:
A[1]

array([4, 5, 6])

In [29]:
A[1, 0]

4

In [30]:
A[1][0]

4

In [31]:
A = np.array([
#.   0, 1, 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [32]:
A[1]

array([4, 5, 6])

In [33]:
A[1][0]

4

In [34]:
A[1, 0]

4

In [35]:
A[0 : 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [37]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [38]:
A[:2, 2:]

array([[3],
       [6]])

In [39]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
A[2]

array([7, 8, 9])

In [41]:
A[1] = np.array([10, 10, 10])

In [42]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [43]:
A[2] = 99

In [44]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [45]:
a = np.array([1, 2, 3, 4])

In [46]:
a.sum()

10

In [47]:
a.mean()

2.5

In [48]:
a.std()

1.118033988749895

In [49]:
a.var()

1.25

In [50]:
A = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

In [51]:
A.sum

<function ndarray.sum>

In [52]:
A.sum()

45

In [53]:
A.mean()

5.0

In [54]:
A.std()

2.581988897471611

In [55]:
A.sum(axis = 0)

array([12, 15, 18])

In [56]:
A.sum(axis=1)

array([ 6, 15, 24])

In [57]:
A.mean(axis=1)

array([2., 5., 8.])

In [58]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [59]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [60]:
a = np.arange(4)

In [61]:
a

array([0, 1, 2, 3])

In [62]:
a + 10

array([10, 11, 12, 13])

In [63]:
a * 10

array([ 0, 10, 20, 30])

In [64]:
a

array([0, 1, 2, 3])

In [65]:
b = np.array([10,10,10,10])

In [67]:
a + b

array([10, 11, 12, 13])

In [68]:
a * b

array([ 0, 10, 20, 30])

In [69]:
a = np.arange(4)

In [70]:
a

array([0, 1, 2, 3])

In [71]:
a[[0, -1]]

array([0, 3])

In [72]:
a[[True, False, False, True]]

array([0, 3])

In [73]:
a >= 2

array([False, False,  True,  True])

In [74]:
a[a >= 2]

array([2, 3])

In [75]:
a.mean()

1.5

In [76]:
a[a >  a.mean()]

array([2, 3])

In [78]:
a[~(a > a.mean())]

array([0, 1])

In [79]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [80]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [81]:
A = np.random.randint(100, size=(3,3))

In [82]:
A

array([[43, 40, 79],
       [32, 43, 13],
       [71,  6, 93]])

In [85]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([43, 79, 43, 71, 93])

In [86]:
A > 30

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [87]:
A[A>30]

array([43, 40, 79, 32, 43, 71, 93])

In [88]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [91]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [92]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [93]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [94]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [95]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
B. T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [98]:
l = list(range(1000))

In [99]:
a = np.arange(1000)

In [100]:
%time np.sum(a ** 2)

CPU times: user 249 µs, sys: 129 µs, total: 378 µs
Wall time: 351 µs


332833500

In [101]:
%time sum([x ** 2 for x in l])

CPU times: user 102 µs, sys: 6 µs, total: 108 µs
Wall time: 113 µs


332833500

In [102]:
np.random.random(size=2)

array([0.73963641, 0.5805698 ])

In [103]:
np.random.normal(size = 2)

array([ 0.19507529, -1.02752751])

In [108]:
np.random.rand(2, 4)

array([[0.64660364, 0.2809396 , 0.57743732, 0.3369219 ],
       [0.80718811, 0.55567143, 0.34927231, 0.41777986]])

In [109]:
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
